### ISSUE TITLE
I can't reference an image in Next.js

### ISSUE THREAD

**Issue by zlrlo** [tkhwang/readable#31]
- image 못가져오는 이슈

**Comment by tkhwang** [comment]
무슨 문제인지 모르겠지만... 그냥 쉽게 하려면...
어딘가 서버에 올려두고 (github의 PR 이나 issue 등의 입력창에 그림을 drag & drop해서 떨어지는 URL 이용해도 가능) 그 URL 을 쓰면 어때 ?
readable logo 도 그렇게 사용하고 있어. 물론 나중에는 제대로 해야겠지.

혹시 issue 가 아닌 사항은 discussion 을 써도 좋을 듯.
https://github.com/tkhwang/readable/discussions

**Comment by zlrlo** [comment]
오 discussion도 있넹
